/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class ViewController {
    
   @GetMapping("/greeting")
    public String greetingForm(Model model) {
        model.addAttribute("greeting", new Greeting());
        return "greeting";
    }

    @PostMapping("/greeting")
    public String greetingSubmit(@ModelAttribute Greeting greeting) {
        return "result";
    }
  
    @GetMapping("/index")
    public String homePage(Model model)
    {
        model.addAttribute("soundboard", new SoundBoard());
        return "index";
    }
    
   /* @GetMapping("/upload")
    public String soundForm(Model model) {
        model.addAttribute("sound", new Sound());
        return "upload";
    }
    */
    @PostMapping("/index")
    public String addNewPage(@ModelAttribute SoundBoard soundboard)
    {
        return "uboard";
    }
    
   /* @Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private SoundRepository soundRepository;
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewSound (@RequestParam Integer buttonNumber
			, @RequestParam String fileName, @RequestParam String color) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
                
		Sound n = new Sound();
		n.setButtonNumber(buttonNumber);
		n.setFileName(fileName);
                n.setColor(color);
		soundRepository.save(n);
                
		return "Saved";
	}*/
        
        
        
        @GetMapping(path="setsound")
        public String setSound(Model model)
        {
            return "setsound";
        }

	


}